#!/bin/bash

inotifywait -qme close_write ./ |
while read path action file; do
  [[ "$file" =~ .*tex$ ]] && make pdf;
  [[ "$file" != "main.tex" ]] && [[ "$file" =~ .*tex$ ]] && echo $file && touch main.tex
done
